#theme: jekyll-theme-leap-day
#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-hacker
#theme: jekyll-theme-merlot
#theme: minima
